"""Task three_x_ui_xray_setup: wrap the official 3x-ui installer.

The task deploys the 3x-ui Xray panel as a system service by wrapping
the official install.sh of the configured repository. The newest release
tag comes from the GitHub releases API
(https://api.github.com/repos/{repo}/releases/latest); the task compares
it with the installed version read from the x-ui binary and with the
enabled and active state of the service. When the installed version
equals the newest release tag and the service is already enabled and
active, the task returns a plain done result with changed=False: the
official installer always tears the panel down and rebuilds it, so it
must not be run on a working panel just to confirm the state. Otherwise
the task frees the fixed panel port (stopping the x-ui service when it
owns the port, terminating an unknown process), downloads the official
install.sh and runs it in non-interactive mode (XUI_NONINTERACTIVE=1)
with the proquint credentials and the panel port passed as env vars
(XUI_USERNAME, XUI_PASSWORD, XUI_WEB_BASE_PATH, XUI_PANEL_PORT). The
installer applies them on first deployment and preserves the current
values on an existing panel with custom credentials, so a rerun never
rotates them.

Stage 2 reads the credentials the panel generated on first start from
/etc/x-ui/install-result.env, logs in through the panel REST API to
verify the session, and stores the credentials in the runtime vault
(/var/lib/pyntara/secrets/pyntara.vault) in a single KeePass entry
named by vault_entry_title. The username and password fields carry the
panel admin credentials; the url field carries the panel base URL; the
notes field carries the additional values (XUI_PANEL_PORT,
XUI_WEB_BASE_PATH, XUI_API_TOKEN, XUI_DB_TYPE) as key=value lines.
Stage 2 runs after every install and on every rerun where the target
state is already reached, so the vault entry is always up to date.

Stage 3 creates a VLESS+REALITY inbound on the configured port through
the panel Bearer-token API. The REALITY keypair is generated through
the panel's getNewX25519Cert endpoint; the private and public keys are
appended to the vault entry notes. On a rerun the task finds the
existing inbound by port and returns done without creating a duplicate.

Stage 4 ensures the panel serves HTTPS when ssl_enabled. A trusted
Let's Encrypt IP certificate is issued when the HTTP-01 challenge can
reach the machine: a machine with a public address on an interface (a
VPS) or a confirmed port-80 forward runs the installer with
XUI_SSL_MODE=ip; a machine behind NAT without a forward gets a
self-signed certificate generated by the task, so the panel never
serves plain HTTP. On a rerun where the installer is skipped, the stage
checks `x-ui setting -getCert`, issues the certificate through acme.sh
when the panel has none, replaces a self-signed certificate with a
trusted one as soon as port 80 becomes reachable, and otherwise keeps
the existing certificate. The result tells the user honestly whether
the certificate is trusted or self-signed and how to obtain a trusted
one. After the installer (and on a rerun) the task brings the panel to
the configured port, migrating it when an earlier install left it on
another port, and syncs install-result.env so its port and scheme match
reality. In force mode on an existing panel the task also applies fresh
proquint credentials and webBasePath directly through `x-ui setting`,
because the installer preserves them on a non-default panel; normal runs
never touch them.

Stage 6 makes this machine a client of the remote server whose vless link
sits in the vault entry named by client_profile_entry_title: the panel
already runs Xray here, so the client is one inbound of that panel that
serves SOCKS5 and HTTP on a local address, and no second Xray process is
installed. Stage 7 routes what enters that inbound: advertising is
dropped, .onion goes to the local tor proxy and .i2p to the local i2pd
proxy, the machine's own names and networks go directly, and the rest
depends on the country the configured services report. A machine outside
Russia sends everything else to the pool of the remote classes, which
carries the remote server and the nodes the panel builds from its
outbound subscriptions; a machine in Russia sends the resources blocked
there and the services that refuse to serve Russia to that pool, reaches
what only answers inside Russia directly, and sends everything else
directly as well. Every category
token is checked against the geodata the panel installed before it is
applied, and every class of destination is then verified against the
running core with its routing test, because the core can hold a rule set
the stored template no longer matches. The client half, the pool of
remote exits included, is built on every machine: the machine that is
the remote server itself never creates the outbound that would connect
it to itself, so its pool carries the subscription nodes only and falls
back to the direct outbound.
"""

import ipaddress
import os
import re
import subprocess
import sys
import tempfile
import time
from dataclasses import replace
from pathlib import Path

from pyntara import metrics, routing_policy, xray_client
from pyntara import xui as xui_client
from pyntara.config import Config, EngineConfig, ThreeXuiXraySetupConfig
from pyntara.context import Context
from pyntara.github_release import fetch_latest_release, release_tag
from pyntara.logger import log_progress as _log
from pyntara.models import TaskResult
from pyntara.tasks.local_vault_setup import open_source_vault
from pyntara.utils import (
    download_command,
    ensure_port_free,
    install_package_once,
    package_is_installed,
    proquint_encode,
    run_command,
    service_is_active,
    service_is_enabled,
    substituted_command,
    task_data_dir,
    trim_whitespace,
    version_from_output,
    version_without_tag_prefix,
)
from pyntara.xray_facts import (
    _bare_address,
    _collect_run_facts,
    _detect_server_ip,
    _forward_upnp_ports,
    _RunFacts,
    _server_share_address,
)

# The IPv4 pattern used to validate an address reported by an echo
# service; a full match only, so garbage is never accepted. The ACME
# port, the certificate locations and the echo services live in the
# [three_x_ui_xray_setup] config table, never as module constants.
IPV4_PATTERN = re.compile(r"\d{1,3}(?:\.\d{1,3}){3}")


def _panel_binary(cfg: ThreeXuiXraySetupConfig) -> Path:
    """The installed panel binary, from its configured file name.

    Every call the task makes to the panel binary is built from this one
    path, so the file name of the binary is a single config value and a
    future release that renames it needs no code change.
    """

    return cfg.install_dir / cfg.binary_file_name


def _panel_command(
    cfg: ThreeXuiXraySetupConfig, template: tuple[str, ...], **values: str
) -> list[str]:
    """The argv of one panel CLI call, with its placeholders filled in.

    The path of the binary enters every call as {binary} and the values
    the call site knows travel as their own placeholders, so the verbs
    and the flags of the tool live in the config table next to the binary
    itself.
    """

    return substituted_command(
        template, {**values, "binary": str(_panel_binary(cfg))}
    )


def _installed_version(
    cfg: ThreeXuiXraySetupConfig, timeout: float
) -> str | None:
    """The installed x-ui version from the binary -v output, or None.

    A missing binary, a nonzero exit or a hang means 3x-ui is not
    installed: the task treats the version as absent and runs the
    installer. The missing executable raises FileNotFoundError (an
    OSError), which subprocess raises regardless of check; the version
    triple is searched in stdout and stderr, because the exact output
    format may change.
    """

    try:
        result = run_command(
            _panel_command(cfg, cfg.panel_version_command),
            check=False,
            capture=True,
            timeout=timeout,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None
    if result.returncode != 0:
        return None
    return version_from_output(result.stdout + "\n" + result.stderr)


def _download_installer(
    engine: EngineConfig,
    cfg: ThreeXuiXraySetupConfig,
    timeout: float,
) -> Path:
    """Download the official installer into a temporary file.

    Returns the path of the downloaded script. The command is the
    engine-wide download call. Raises RuntimeError when curl fails, so the
    caller reports the reason.
    """

    _fd, name = tempfile.mkstemp(prefix="x-ui-install-", suffix=".sh")
    script_path = Path(name)
    try:
        run_command(
            download_command(engine, script_path, cfg.install_script_url),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        try:
            script_path.unlink()
        except OSError:
            pass
        raise RuntimeError(
            f"cannot download installer {cfg.install_script_url}: {exc}"
        ) from None
    return script_path


def _credential_env(cfg: ThreeXuiXraySetupConfig) -> dict[str, str]:
    """The XUI_ credential and port env vars for the installer.

    The panel port is fixed to cfg.panel_port; the username, password
    and webBasePath are proquint encodings of fresh random bytes, whose
    length comes from the config (docs/spec/3x-ui.md, Credentials
    boundary). The installer applies
    these values only when the panel is in the default state (first
    deployment); on an existing panel with custom credentials it
    preserves the current values, so a rerun never rotates them. The
    applied values land in /etc/x-ui/install-result.env for stage 2.
    """

    keys = cfg.panel_environment_keys
    return {
        keys["username"]: proquint_encode(
            os.urandom(cfg.random_username_bytes), ""
        ),
        keys["password"]: proquint_encode(
            os.urandom(cfg.random_secret_bytes), ""
        ),
        keys["web_base_path"]: proquint_encode(
            os.urandom(cfg.random_secret_bytes), "-"
        ),
        keys["panel_port"]: str(cfg.panel_port),
    }


def _installer_environment(
    cfg: ThreeXuiXraySetupConfig, extra_env: dict[str, str]
) -> dict[str, str]:
    """The environment the official installer runs in.

    The installer is a third-party shell script that resolves python3 from
    PATH for its own steps. The engine runs inside the project venv, whose
    bin directory would win that lookup with an interpreter that carries
    none of the installer's dependencies, so the venv leaves PATH and
    VIRTUAL_ENV is cleared: the installer then uses the system python3,
    where its packages live. The XUI_* values of extra_env stay untouched.
    """

    environment = dict(os.environ)
    venv_root = environment.get("VIRTUAL_ENV") or sys.prefix
    environment["PATH"] = os.pathsep.join(
        entry
        for entry in environment.get("PATH", "").split(os.pathsep)
        if entry
        and not (entry == venv_root or entry.startswith(f"{venv_root}{os.sep}"))
    )
    environment["VIRTUAL_ENV"] = ""
    environment[cfg.panel_environment_keys["noninteractive"]] = "1"
    environment.update(extra_env)
    return environment


def _run_installer(
    cfg: ThreeXuiXraySetupConfig,
    script_path: Path,
    timeout: float,
    extra_env: dict[str, str],
) -> None:
    """Run the downloaded official installer in non-interactive mode.

    XUI_NONINTERACTIVE=1 makes the installer replace every interactive
    prompt with an environment-variable value or a sane default. The
    extra env carries the proquint credentials and the fixed panel port;
    the installer applies them on first deployment and preserves the
    current values on an existing panel with custom credentials. Raises
    CalledProcessError or TimeoutExpired, so the caller reports the
    reason.
    """

    try:
        run_command(
            substituted_command(
                cfg.installer_run_command, {"script_path": str(script_path)}
            ),
            extra_env=_installer_environment(cfg, extra_env),
            timeout=timeout,
        )
    finally:
        try:
            script_path.unlink()
        except OSError:
            pass


def _wait_active(
    engine: EngineConfig,
    service_name: str,
    wait_seconds: int,
    check_delay_seconds: int,
    timeout: float,
) -> bool:
    """True when the service reports active within the readiness budget.

    The service may report activating for a moment after start, so the
    check is repeated with a pause until the budget runs out. The budget
    is a number of seconds and not a count of checks, because a count with
    a fixed pause is a hidden fixed sleep that reports a slow machine as a
    service that never became active.
    """

    started = time.monotonic()
    while True:
        if service_is_active(engine, service_name, timeout):
            return True
        if time.monotonic() - started >= wait_seconds:
            return False
        time.sleep(check_delay_seconds)


def _build_notes(cfg: ThreeXuiXraySetupConfig, env: dict[str, str]) -> str:
    """Build the notes field for the vault entry from the env dict.

    The notes carry the additional values that do not fit into the
    standard KeePass fields: the panel port, the web base path, the API
    token and the database type, under the names the panel environment
    keys of the config give them. Each is written as key=value on its
    own line.
    """

    lines: list[str] = []
    keys = cfg.panel_environment_keys
    for key in (
        keys["panel_port"],
        keys["web_base_path"],
        keys["api_token"],
        keys["db_type"],
    ):
        value = env.get(key)
        if value:
            lines.append(f"{key}={value}")
    return "\n".join(lines)


def _stage2(
    cfg: ThreeXuiXraySetupConfig,
    full_config: Config,
    timeout: float,
) -> TaskResult | None:
    """Run stage 2: read credentials, verify session, store in vault.

    Returns None on success (the vault entry was created or is already
    current). Returns a TaskResult when a non-fatal problem occurs
    (missing install-result.env, unreachable panel, vault unavailable),
    so the caller returns it as a done-with-warnings result.
    """

    # Read the credentials the panel generated on first start.
    try:
        env = xui_client.panel_environment(cfg, timeout)
    except FileNotFoundError:
        return TaskResult(
            success=True,
            changed=False,
            warnings=("install-result.env not found: panel may not have started yet",),
        )
    except RuntimeError as exc:
        return TaskResult(
            success=True,
            changed=False,
            warnings=(str(exc),),
        )
    _log("stage 2: read credentials from install-result.env")

    # Verify the session through the panel REST API.
    if not xui_client.login_and_verify(cfg, env, timeout):
        _log("stage 2: panel login failed, credentials may be stale")
        return TaskResult(
            success=True,
            changed=False,
            warnings=("panel login failed: panel may be unreachable or credentials invalid",),
        )
    _log("stage 2: panel login successful")

    # Open the runtime vault.
    kp = metrics.open_runtime_vault(full_config)
    if kp is None:
        return TaskResult(
            success=True,
            changed=False,
            warnings=("runtime vault unavailable: credentials not stored",),
        )
    _log("stage 2: runtime vault opened")

    # Build the entry values.
    keys = cfg.panel_environment_keys
    base_url = xui_client.build_panel_url(
        cfg.panel_http_address,
        env.get(keys["panel_port"], ""),
        env.get(keys["web_base_path"]),
        scheme=env.get(keys["scheme"], cfg.panel_url_schemes["http"]),
    )
    username = env.get(keys["username"], "")
    password = env.get(keys["password"], "")
    notes = _build_notes(cfg, env)

    # Find or create the entry.
    entry = kp.find_entries(
        title=cfg.vault_entry_title,
        group=kp.root_group,
        recursive=False,
        first=True,
    )
    if entry is not None:
        # Entry exists: update if values differ.
        if (
            entry.username == username
            and entry.password == password
            and (entry.url or "") == base_url
            and (entry.notes or "") == notes
        ):
            _log("stage 2: vault entry already current")
            return None
        entry.username = username
        entry.password = password
        entry.url = base_url
        entry.notes = notes
        _log("stage 2: updating existing vault entry")
    else:
        kp.add_entry(
            kp.root_group,
            cfg.vault_entry_title,
            username,
            password,
            url=base_url,
            notes=notes,
        )
        _log("stage 2: creating new vault entry")

    kp.save(filename=str(full_config.local_vault_setup.local_vault_path))
    _log("stage 2: vault entry saved")
    return None


def _ensure_inbound_security(
    cfg: ThreeXuiXraySetupConfig,
    env: dict[str, str],
    inbound: dict[str, object],
    timeout: float,
) -> tuple[bool, tuple[str, ...]]:
    """Ensure the inbound carries the REALITY key pair the panel needs.

    The panel writes pbk into a share link only when the public key sits
    in the nested realitySettings.settings block, so the inbound the task
    owns must carry both halves of the pair. The pair is taken from the
    panel itself: getNewX25519Cert returns both keys and both are written
    back through one inbound update. An inbound that already carries the
    public key is left alone, so a rerun is a no-op. Returns (changed,
    warnings): a step that cannot be applied is a warning, never an error,
    so the rest of the task continues.
    """

    fields = cfg.xray_field_keys
    stream = inbound.get(fields["stream_settings"])
    if not isinstance(stream, dict):
        return False, ("inbound has no stream settings",)
    reality = stream.get(fields["reality_settings"])
    if not isinstance(reality, dict):
        return False, ("inbound has no REALITY settings",)
    stored = reality.get(fields["settings"])
    if isinstance(stored, dict) and stored.get(fields["public_key"]):
        return False, ()
    keypair = xui_client.generate_reality_key(cfg, env, timeout)
    if keypair is None:
        return False, ("cannot read the REALITY key pair from the panel",)
    private_key, public_key = keypair
    reality[fields["private_key"]] = private_key
    reality[fields["settings"]] = {
        fields["public_key"]: public_key,
        fields["fingerprint"]: cfg.reality_fingerprint,
    }
    stream[fields["reality_settings"]] = reality
    inbound[fields["stream_settings"]] = stream
    ok, message = xui_client.update_inbound(cfg, env, inbound, timeout)
    if not ok:
        return False, (f"inbound update failed: {message}",)
    _log("inbound REALITY key pair issued by the panel and stored")
    return True, ()


def _stage3(
    cfg: ThreeXuiXraySetupConfig, payload_template: str, timeout: float
) -> TaskResult | None:
    """Run stage 3: create the universal server inbound.

    Reads the panel credentials from install-result.env, searches for an
    existing inbound on the configured port, and creates a VLESS+REALITY
    inbound when none exists. The REALITY keypair is generated through
    the panel API and the keys are appended to the vault entry notes.

    Returns None on success (inbound created or already exists). Returns
    a TaskResult when a non-fatal problem occurs (missing env, unreachable
    panel, vault unavailable), so the caller returns it as a
    done-with-warnings result.
    """

    # Read the credentials the panel generated on first start.
    try:
        env = xui_client.panel_environment(cfg, timeout)
    except FileNotFoundError:
        return TaskResult(
            success=True,
            changed=False,
            warnings=("install-result.env not found: panel may not have started yet",),
        )
    except RuntimeError as exc:
        return TaskResult(
            success=True,
            changed=False,
            warnings=(str(exc),),
        )
    _log("stage 3: read credentials from install-result.env")

    # Check if an inbound on the configured port already exists.
    existing = xui_client.find_inbound_by_port(cfg, env, cfg.inbound_port, timeout)
    if existing is not None:
        _log(f"stage 3: inbound on port {cfg.inbound_port} already exists")
        updated, security_warnings = _ensure_inbound_security(
            cfg, env, existing, timeout
        )
        if security_warnings:
            return TaskResult(
                success=True, changed=updated, warnings=security_warnings
            )
        if updated:
            return TaskResult(
                success=True, changed=True, message="inbound share data updated"
            )
        return None
    _log(f"stage 3: no inbound on port {cfg.inbound_port}, will create")

    # Generate a REALITY keypair through the panel API.
    keypair = xui_client.generate_reality_key(cfg, env, timeout)
    if keypair is None:
        return TaskResult(
            success=True,
            changed=False,
            warnings=("failed to generate REALITY keypair: panel may be unreachable",),
        )
    private_key, public_key = keypair
    _log("stage 3: REALITY keypair generated")

    # Build and send the inbound creation payload from the configured
    # template, so the fields and protocol words of the panel API live in
    # task_data/ and not in this module.
    payload = xui_client.build_vless_reality_payload(
        payload_template,
        port=cfg.inbound_port,
        remark=cfg.inbound_remark,
        dest=cfg.reality_dest,
        server_names=cfg.reality_server_names,
        private_key=private_key,
        public_key=public_key,
        short_id=cfg.reality_short_id,
        fingerprint=cfg.reality_fingerprint,
        sniffing_protocols=cfg.inbound_sniffing_protocols,
    )
    ok, msg = xui_client.create_inbound(cfg, env, payload, timeout)
    if not ok:
        _log(f"stage 3: inbound creation failed: {msg}")
        return TaskResult(
            success=True,
            changed=False,
            warnings=(f"inbound creation failed: {msg}",),
        )
    _log(f"stage 3: inbound created ({msg})")

    return TaskResult(success=True, changed=True, message="inbound created")


def _notes_map(notes: str) -> dict[str, str]:
    """Parse the key=value lines of a vault entry into a dict."""

    values: dict[str, str] = {}
    for line in notes.splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


def _connection_notes(
    cfg: ThreeXuiXraySetupConfig,
    address: str,
    email: str,
    client_id: str,
    sub_id: str,
    public_key: str,
    private_key: str,
) -> str:
    """The connection profile as the key=value lines of the vault notes.

    The canonical share link lives in the entry url field, so the notes
    carry the parameters a client needs to build its own configuration
    and the keys that describe the server side of the connection.
    """

    lines = [
        f"SERVER_ADDRESS={address}",
        f"SERVER_PORT={cfg.inbound_port}",
        f"DEST={cfg.reality_dest}",
        f"SERVER_NAME={cfg.reality_server_names[0]}",
        f"CLIENT_EMAIL={email}",
        f"CLIENT_ID={client_id}",
        f"SUB_ID={sub_id}",
        f"SHORT_ID={cfg.reality_short_id}",
        f"FINGERPRINT={cfg.reality_fingerprint}",
        f"REALITY_PUBLIC_KEY={public_key}",
        f"REALITY_PRIVATE_KEY={private_key}",
    ]
    return "\n".join(lines)


def _stage_connection(
    cfg: ThreeXuiXraySetupConfig,
    full_config: Config,
    timeout: float,
    facts: _RunFacts,
) -> TaskResult | None:
    """Ensure the panel has a client and the vault carries its profile.

    Three independent steps, each reported as a warning instead of an
    error: the panel share address is set so rendered links carry a real
    host, one client is ensured with an identity reused from the vault
    entry, and the profile with the canonical share link and the REALITY
    keys is written into that entry. Returns None when nothing changed, a
    TaskResult carrying changed and the warnings otherwise.
    """

    try:
        env = xui_client.panel_environment(cfg, timeout)
    except FileNotFoundError:
        return TaskResult(
            success=True,
            changed=False,
            warnings=("install-result.env not found: panel may not have started yet",),
        )
    except RuntimeError as exc:
        return TaskResult(success=True, changed=False, warnings=(str(exc),))
    _log("stage 5: read credentials from install-result.env")

    inbound = xui_client.find_inbound_by_port(cfg, env, cfg.inbound_port, timeout)
    if inbound is None:
        return TaskResult(
            success=True,
            changed=False,
            warnings=(
                f"no inbound on port {cfg.inbound_port}: connection profile not stored",
            ),
        )

    warnings: list[str] = []
    changed = False

    # The share address: the panel renders the link host from it, and only
    # the configured strategy makes the panel use it. The address comes
    # from the public IPv4 detection, the yggdrasil node address or the
    # value the panel already stores, in that order.
    address = _server_share_address(cfg, full_config, inbound, facts)
    if address is None:
        warnings.append(
            "no server address available: panel links keep the default host"
        )
    elif inbound.get("shareAddr") != address:
        inbound["shareAddrStrategy"] = cfg.share_addr_strategy
        inbound["shareAddr"] = address
        ok, message = xui_client.update_inbound(cfg, env, inbound, timeout)
        if ok:
            changed = True
            _log(f"panel share address set to {address}")
        else:
            address = None
            warnings.append(f"cannot set the panel share address: {message}")

    # The client identity comes from the vault entry when it is already
    # there, so a rerun reuses the same client instead of adding another.
    kp = metrics.open_runtime_vault(full_config)
    stored: dict[str, str] = {}
    if kp is None:
        warnings.append("runtime vault unavailable: connection profile not stored")
    else:
        entry = kp.find_entries(
            title=cfg.connection_vault_entry_title,
            group=kp.root_group,
            recursive=False,
            first=True,
        )
        if entry is not None:
            stored = _notes_map(entry.notes or "")
    email, client_id, sub_id = _client_identity(cfg, stored)

    inbound_id = inbound.get("id")
    if not isinstance(inbound_id, int):
        return TaskResult(
            success=True,
            changed=changed,
            warnings=tuple(warnings)
            + ("inbound has no id: connection profile not stored",),
        )
    if xui_client.find_client(cfg, env, email, timeout) is None:
        ok, message = xui_client.create_client(
            cfg, env, inbound_id, client_id, email, sub_id, timeout
        )
        if not ok:
            return TaskResult(
                success=True,
                changed=changed,
                warnings=tuple(warnings) + (f"cannot create the client: {message}",),
            )
        changed = True
        _log(f"client ensured: {email}")

    links = xui_client.client_links(cfg, env, email, timeout)
    link = links[0] if links else ""
    if not link:
        warnings.append("panel returned no share link: connection profile not stored")
    if kp is None or not link:
        return TaskResult(success=True, changed=changed, warnings=tuple(warnings))

    fields = cfg.xray_field_keys
    stream = inbound.get(fields["stream_settings"])
    reality_map = (
        stream.get(fields["reality_settings"])
        if isinstance(stream, dict)
        else None
    )
    reality = reality_map if isinstance(reality_map, dict) else {}
    settings_block = reality.get(fields["settings"])
    public_key = ""
    if isinstance(settings_block, dict):
        public_key = str(settings_block.get(fields["public_key"]) or "")
    private_key = str(reality.get(fields["private_key"]) or "")

    notes = _connection_notes(
        cfg,
        _bare_address(address) if address else "",
        email,
        client_id,
        sub_id,
        public_key,
        private_key,
    )
    entry = kp.find_entries(
        title=cfg.connection_vault_entry_title,
        group=kp.root_group,
        recursive=False,
        first=True,
    )
    if (
        entry is not None
        and (entry.notes or "") == notes
        and (entry.url or "") == link
    ):
        return TaskResult(success=True, changed=changed, warnings=tuple(warnings))
    if entry is not None:
        entry.username = _bare_address(address) if address else ""
        entry.url = link
        entry.notes = notes
    else:
        kp.add_entry(
            kp.root_group,
            cfg.connection_vault_entry_title,
            _bare_address(address) if address else "",
            "",
            url=link,
            notes=notes,
        )
    kp.save(filename=str(full_config.local_vault_setup.local_vault_path))
    _log(f"connection profile stored in {cfg.connection_vault_entry_title}")
    return TaskResult(
        success=True,
        changed=True,
        message="connection profile stored",
        warnings=tuple(warnings),
    )


def _read_inbound_payload_template(
    cfg: ThreeXuiXraySetupConfig, ctx: Context
) -> str:
    """The text of the configured inbound payload template.

    The document lives in task_data/<task>/ of the clone the run started
    from; it holds the field names and the protocol words of the panel
    API, so a panel version that renames a field is answered in the
    template. Reading it is the only step of the task that can fail before
    the panel is touched, so the caller reports an unreadable template as
    a warning of a completed task and never as a traceback.
    """

    return (
        task_data_dir(ctx.repo_root, ctx.task_name)
        / cfg.inbound_payload_template_file_name
    ).read_text(encoding="utf-8")


def _client_identity(
    cfg: ThreeXuiXraySetupConfig, stored: dict[str, str]
) -> tuple[str, str, str]:
    """The email, client id and subscription id of the panel client.

    An identity already stored for this panel wins, so a rerun reuses the
    client instead of adding another; a first run generates one, and the
    length of the random part of each value comes from the config.
    """

    email = stored.get("CLIENT_EMAIL") or proquint_encode(
        os.urandom(cfg.random_username_bytes), "-"
    )
    client_id = stored.get("CLIENT_ID") or proquint_encode(
        os.urandom(cfg.random_secret_bytes), "-"
    )
    sub_id = stored.get("SUB_ID") or proquint_encode(
        os.urandom(cfg.random_sub_id_bytes), ""
    )
    return email, client_id, sub_id


def _is_private_ipv4(address: str, networks: tuple[str, ...]) -> bool:
    """True when the address falls inside one of the configured networks.

    The networks are the private IPv4 ranges of the section, the RFC1918
    set by default. A machine whose own interface carries only an address
    from such a range cannot serve the Let's Encrypt HTTP-01 challenge on
    the ACME port unless the router forwards it. The standard library
    decides the containment, so the notation of the config is the usual
    CIDR notation and no prefix arithmetic lives here.
    """

    try:
        parsed = ipaddress.ip_address(address)
    except ValueError:
        return False
    return any(
        parsed in ipaddress.ip_network(network, strict=True)
        for network in networks
    )


def _probe_port_80_forward(
    cfg: ThreeXuiXraySetupConfig, timeout: float, facts: _RunFacts
) -> bool:
    """True when external port 80 is forwarded back to this machine.

    Binds a temporary HTTP listener on the ACME port and connects to the
    detected public address from the machine itself. A successful
    connection means the router forwards external port 80 here; any
    failure (no forward, no hairpin NAT, busy port, missing python3) is
    treated as not confirmed.
    """

    public_ip = _detect_server_ip(facts)
    if public_ip is None:
        return False
    _log(
        f"probing whether external port {cfg.acme_port} reaches "
        f"{public_ip} here"
    )
    try:
        listener = subprocess.Popen(
            substituted_command(
                cfg.acme_port_listener_command,
                {"port": str(cfg.acme_port)},
            ),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except OSError:
        return False
    try:
        time.sleep(cfg.probe_listener_start_seconds)
        probe_url = cfg.port_forward_probe_url_format.format(
            host=public_ip, port=cfg.acme_port
        )
        try:
            result = run_command(
                substituted_command(
                    cfg.port_forward_probe_command,
                    {
                        "timeout_seconds": str(
                            cfg.probe_port_80_timeout_seconds
                        )
                    },
                )
                + [probe_url],
                check=False,
                capture=True,
                timeout=timeout,
            )
        except (subprocess.TimeoutExpired, OSError):
            _log(f"port {cfg.acme_port} did not answer: no forward confirmed")
            return False
        if result.returncode != 0:
            _log(f"port {cfg.acme_port} did not answer: no forward confirmed")
        else:
            _log(f"port {cfg.acme_port} answered: the forward is confirmed")
        return result.returncode == 0
    finally:
        listener.terminate()
        try:
            listener.wait(timeout=cfg.probe_timeout_seconds)
        except subprocess.TimeoutExpired:
            listener.kill()


def _ssl_reachable(
    cfg: ThreeXuiXraySetupConfig, timeout: float, facts: _RunFacts
) -> bool:
    """Whether the Let's Encrypt HTTP-01 challenge can be served.

    A machine with a public address on an interface (a VPS) serves the
    challenge directly. A machine behind NAT can only when the router
    forwards external port 80 back to it, which the self-test confirms.
    When the local address cannot be determined the attempt is allowed,
    so a working setup is never skipped by accident.
    """

    local = facts.local_addresses
    if not local or not _is_private_ipv4(local[0], cfg.private_ipv4_networks):
        return True
    return _probe_port_80_forward(cfg, timeout, facts)


def _actual_panel_port(
    cfg: ThreeXuiXraySetupConfig, timeout: float
) -> str | None:
    """The panel port from `x-ui setting -show true`, or None.

    The setting output prints "port: N" among other values; the first
    matching line wins. None when the panel cannot be queried or the
    line is absent.
    """

    try:
        result = run_command(
            _panel_command(cfg, cfg.panel_settings_query_command),
            check=False,
            capture=True,
            timeout=timeout,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None
    for line in (result.stdout + "\n" + result.stderr).splitlines():
        match = re.search(r"^\s*port:\s*(\d+)\s*$", line)
        if match:
            return match.group(1)
    return None


def _converge_panel_port(
    engine: EngineConfig, cfg: ThreeXuiXraySetupConfig, timeout: float
) -> tuple[bool, str | None]:
    """Bring the panel to the configured port; returns (changed, message).

    Reads the actual panel port from `x-ui setting -show true`. When it
    differs from cfg.panel_port the target port is freed, the new port
    is set through `x-ui setting -port` and the panel restarts so the
    change takes effect. Raises RuntimeError when the port stays
    occupied or the panel cannot be reconfigured. An unreadable panel
    port is reported as a message with changed=False, so a transient
    read failure does not fail the task.
    """

    actual = _actual_panel_port(cfg, timeout)
    if actual is None:
        return False, "cannot read panel port"
    if actual == str(cfg.panel_port):
        return False, None
    _log(f"moving the panel from port {actual} to {cfg.panel_port}")
    try:
        ensure_port_free(
            engine,
            cfg.panel_port,
            cfg.service_unit_name,
            timeout,
            service_process_name=cfg.service_process_name,
        )
    except RuntimeError as exc:
        raise RuntimeError(
            f"panel port {cfg.panel_port} still occupied: {exc}"
        ) from None
    try:
        run_command(
            _panel_command(
                cfg,
                cfg.panel_port_command,
                port=str(cfg.panel_port),
            ),
            timeout=timeout,
        )
        run_command(
            substituted_command(
                cfg.service_restart_command,
                {"service_unit_name": cfg.service_unit_name},
            ),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise RuntimeError(
            f"cannot move panel to port {cfg.panel_port}: {exc}"
        ) from None
    return True, f"panel port moved to {cfg.panel_port}"


def _wait_panel_http(
    cfg: ThreeXuiXraySetupConfig,
    timeout: float,
) -> bool:
    """True when the panel answers HTTP on the configured port.

    Polls the panel's csrf-token endpoint until it answers. A port
    migration restarts the panel and the HTTP listener can trail the
    systemd active state by a moment; stage 2 would otherwise report a
    false login failure. The scheme follows the configured certificate
    and TLS is not verified, mirroring the API client. An unreadable
    install-result.env leaves the web base path empty, which still
    detects the listener. The budget in seconds, the pause between two
    checks and the probe timeout come from the config: a slow link must
    not be reported as an unreachable panel.
    """

    budget = cfg.panel_listener_wait_seconds
    delay = cfg.readiness_check_delay_seconds
    _log(
        f"waiting for the panel HTTP listener on port {cfg.panel_port} "
        f"(up to {budget} s)"
    )
    web_path = ""
    try:
        env = xui_client.parse_install_result_env(
            Path(cfg.install_result_env_path),
            xui_client.panel_required_environment_keys(cfg),
        )
        web_path = env.get(cfg.panel_environment_keys["web_base_path"], "")
    except (FileNotFoundError, RuntimeError, OSError):
        pass
    try:
        scheme = xui_client.panel_scheme(cfg, timeout)
    except (subprocess.TimeoutExpired, OSError):
        scheme = "http"
    base_url = xui_client.build_panel_url(
        cfg.panel_http_address, str(cfg.panel_port), web_path, scheme=scheme
    )
    started = time.monotonic()
    while True:
        try:
            result = run_command(
                substituted_command(
                    cfg.panel_probe_command,
                    {"timeout_seconds": str(cfg.probe_timeout_seconds)},
                )
                + [f"{base_url}{cfg.panel_csrf_token_path}"],
                check=False,
                capture=True,
                timeout=timeout,
            )
        except (subprocess.TimeoutExpired, OSError):
            return False
        if result.returncode == 0:
            return True
        if time.monotonic() - started >= budget:
            return False
        time.sleep(delay)


def _rewrite_env(path: Path, updates: dict[str, str]) -> bool:
    """Apply key=value updates to an env file, preserving line order.

    Reads the file, keeps the order of the existing keys, appends keys
    that are not present yet, replaces the given pairs and writes back
    only when something changed. Returns True when the file was
    rewritten. Shared by the install-result.env sync and the credential
    takeover, so the file is written through one mechanism.
    """

    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    values: dict[str, str] = {}
    order: list[str] = []
    for line in text.splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
            order.append(key.strip())
    changed = False
    for key, value in updates.items():
        if values.get(key) != value:
            values[key] = value
            changed = True
    if not changed:
        return False
    new_lines = []
    for key in order:
        new_lines.append(f"{key}={values[key]}")
    for key, value in values.items():
        if key not in order:
            new_lines.append(f"{key}={value}")
    try:
        path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    except OSError:
        return False
    return True


def _sync_install_result_env(
    cfg: ThreeXuiXraySetupConfig, timeout: float
) -> bool:
    """Sync install-result.env so its port, scheme and url match reality.

    The panel port after the convergence and the scheme after the HTTPS
    stage set the certificate are written through the shared env rewrite,
    so consumers never read a stale port or a scheme the panel does not
    serve.
    """

    env_path = Path(cfg.install_result_env_path)
    if not env_path.is_file():
        return False
    try:
        text = env_path.read_text(encoding="utf-8")
    except OSError:
        return False
    values: dict[str, str] = {}
    for line in text.splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    port = str(cfg.panel_port)
    updates: dict[str, str] = {"XUI_PANEL_PORT": port}
    url = values.get("XUI_ACCESS_URL")
    if url is not None:
        try:
            scheme = xui_client.panel_scheme(cfg, timeout)
        except (subprocess.TimeoutExpired, OSError):
            scheme = None
        old_scheme = url.split("://", 1)[0] if "://" in url else "http"
        host = ""
        if "://" in url:
            host = url.split("://", 1)[1].split("/", 1)[0]
            if ":" in host:
                host = host.split(":", 1)[0]
        new_url = f"{scheme or old_scheme}://{host}:{port}"
        web_path = values.get("XUI_WEB_BASE_PATH", "").strip("/")
        if web_path:
            new_url += f"/{web_path}"
        if url != new_url:
            updates["XUI_ACCESS_URL"] = new_url
    _log(f"syncing {env_path} with the real panel port and scheme")
    return _rewrite_env(env_path, updates)


def _takeover_credentials(
    cfg: ThreeXuiXraySetupConfig,
    timeout: float,
    creds: dict[str, str],
) -> tuple[bool, str]:
    """Force-apply fresh proquint credentials and webBasePath to the panel.

    Runs in force mode on an existing panel: the installer preserves the
    current credentials and webBasePath on a non-default panel, so the
    task applies the fresh values it generated for the installer directly
    through `x-ui setting`, rewrites install-result.env through the shared
    helper and restarts the panel, so stage 2 stores the new values.
    Returns (changed, message); a failure returns (False, error).
    """

    username = creds.get("XUI_USERNAME", "")
    password = creds.get("XUI_PASSWORD", "")
    web_base_path = creds.get("XUI_WEB_BASE_PATH", "")
    try:
        run_command(
            _panel_command(
                cfg,
                cfg.panel_credentials_command,
                username=username,
                password=password,
                web_base_path=web_base_path,
            ),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        return False, f"cannot set panel credentials: {exc}"
    _rewrite_env(
        Path(cfg.install_result_env_path),
        {
            "XUI_USERNAME": username,
            "XUI_PASSWORD": password,
            "XUI_WEB_BASE_PATH": web_base_path,
        },
    )
    try:
        run_command(
            substituted_command(
                cfg.service_restart_command,
                {"service_unit_name": cfg.service_unit_name},
            ),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        return False, f"cannot restart {cfg.service_unit_name}: {exc}"
    _wait_panel_http(cfg, timeout)
    return True, (
        f"panel credentials and webBasePath set to fresh proquint "
        f"values ({web_base_path})"
    )


def _acme_path(cfg: ThreeXuiXraySetupConfig) -> Path:
    """The acme.sh binary under the current user's home directory.

    The directory and the file name of the tool are config values, so a
    release that installs itself elsewhere is a config change.
    """

    return Path.home() / cfg.acme_dir_relative_path / cfg.acme_file_name


def _ensure_acme(cfg: ThreeXuiXraySetupConfig, timeout: float) -> bool:
    """Install acme.sh via get.acme.sh when it is not present yet.

    True when the acme.sh binary exists after the call. A missing binary
    after an install attempt is a failure.
    """

    acme = _acme_path(cfg)
    if acme.is_file():
        return True
    try:
        run_command(
            list(cfg.acme_install_command),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False
    return acme.is_file()


def _issue_ip_certificate(
    cfg: ThreeXuiXraySetupConfig, ip: str, timeout: float
) -> tuple[bool, str]:
    """Issue and install a Let's Encrypt IP certificate for the address.

    Mirrors the official installer's setup_ip_certificate: runs acme.sh
    with the shortlived profile over the standalone HTTP-01 listener,
    installs the certificate under /root/cert/ip and points the panel at
    it through `x-ui cert`. Returns (ok, message).
    """

    if not _ensure_acme(cfg, timeout):
        return False, "acme.sh install failed"
    # acme.sh installcert does not create the certificate directory
    # itself; the installer creates it with mkdir -p before the call.
    cfg.cert_dir.mkdir(parents=True, exist_ok=True)
    acme = str(_acme_path(cfg))
    reload_cmd = cfg.acme_reload_command.format(
        service_unit_name=cfg.service_unit_name
    )
    steps = [
        substituted_command(cfg.acme_set_default_ca_command, {"acme": acme}),
        substituted_command(
            cfg.acme_issue_command,
            {"acme": acme, "domain": ip, "http_port": str(cfg.acme_port)},
        ),
        substituted_command(
            cfg.acme_installcert_command,
            {
                "acme": acme,
                "domain": ip,
                "key_file": str(cfg.cert_privkey),
                "fullchain_file": str(cfg.cert_fullchain),
                "reload_command": reload_cmd,
            },
        ),
        substituted_command(cfg.acme_upgrade_command, {"acme": acme}),
    ]
    for command in steps:
        try:
            result = run_command(
                command, check=False, capture=True, timeout=timeout
            )
        except (subprocess.TimeoutExpired, OSError) as exc:
            return False, f"acme.sh step failed: {exc}"
        if result.returncode != 0:
            return False, (
                f"acme.sh step failed (exit {result.returncode}): "
                f"{' '.join(command[1:3])}"
            )
    if not cfg.cert_fullchain.is_file() or not cfg.cert_privkey.is_file():
        return False, "certificate files missing after acme.sh installcert"
    try:
        os.chmod(cfg.cert_privkey, cfg.cert_privkey_file_mode)
        os.chmod(cfg.cert_fullchain, cfg.cert_fullchain_file_mode)
    except OSError as exc:
        return False, f"cannot secure certificate permissions: {exc}"
    try:
        run_command(
            _panel_command(
                cfg,
                cfg.panel_certificate_command,
                fullchain=str(cfg.cert_fullchain),
                privkey=str(cfg.cert_privkey),
            ),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        return False, f"cannot point panel at certificate: {exc}"
    # The panel only serves TLS after a restart; the acme.sh reloadcmd
    # already restarted it before the certificate paths were set, so the
    # restart must happen again after x-ui cert.
    try:
        run_command(
            substituted_command(
                cfg.service_restart_command,
                {"service_unit_name": cfg.service_unit_name},
            ),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        return False, f"cannot restart {cfg.service_unit_name}: {exc}"
    return True, "certificate issued"


def _ensure_openssl(engine: EngineConfig, timeout: float) -> bool:
    """True when the openssl binary is present, installing it if needed.

    The self-signed certificate is generated with the external openssl
    tool (project rule: use a ready tool instead of writing a
    generator); a missing package is installed through the shared
    helper, so the setup never depends on a preinstalled package.
    """

    if package_is_installed(engine, "openssl", timeout):
        return True
    _log("openssl is missing, installing the package")
    ok, _ = install_package_once(engine, "openssl", timeout)
    if ok:
        _log("openssl installed")
    return ok


def _certificate_subject_name(
    cfg: ThreeXuiXraySetupConfig, timeout: float, facts: _RunFacts
) -> str:
    """The CN for the self-signed certificate: a known address if any.

    The detected public address is preferred, then the local IPv4, then
    a fixed name. The certificate is self-signed and untrusted either
    way, so the subject only labels it and does not affect the handshake.
    """

    ip = _detect_server_ip(facts)
    if ip is None and facts.local_addresses:
        ip = facts.local_addresses[0]
    return ip or "3x-ui"


def _self_signed_not_expired(
    cfg: ThreeXuiXraySetupConfig, timeout: float
) -> bool:
    """True when the self-signed certificate is still valid.

    A missing or broken openssl is treated as valid so a rerun never
    churns a working panel: without openssl the certificate cannot be
    regenerated anyway.
    """

    try:
        result = run_command(
            substituted_command(
                cfg.openssl_check_command,
                {"fullchain": str(cfg.self_signed_cert_fullchain)},
            ),
            check=False,
            capture=True,
            timeout=timeout,
        )
    except (subprocess.TimeoutExpired, OSError):
        return True
    return result.returncode == 0


def _ensure_self_signed_cert(
    engine: EngineConfig,
    cfg: ThreeXuiXraySetupConfig,
    timeout: float,
    facts: _RunFacts,
) -> tuple[bool, str]:
    """Ensure the panel serves HTTPS with a self-signed certificate.

    When the panel already points at our self-signed files and they are
    still valid, nothing changes. Otherwise the files are generated with
    openssl (the package is installed when absent), the panel is pointed
    at them through `x-ui cert` and restarted. Returns (changed,
    message): (False, "") when nothing was needed, (True, "self-signed
    certificate configured") after the setup, and (False, error) when
    the panel cannot be brought to HTTPS and stays on HTTP.
    """

    self_signed_path = str(cfg.self_signed_cert_fullchain)
    current = xui_client.panel_cert_value(cfg, timeout)
    if current is not None and current != self_signed_path:
        return False, ""
    files_ok = (
        cfg.self_signed_cert_fullchain.is_file()
        and cfg.self_signed_cert_privkey.is_file()
    )
    needs_generation = not files_ok
    if files_ok:
        needs_generation = not _self_signed_not_expired(cfg, timeout)
    if current == self_signed_path and not needs_generation:
        _log("self-signed certificate already configured")
        return False, ""
    if needs_generation:
        _log("generating a self-signed certificate")
        if not _ensure_openssl(engine, timeout):
            return (
                False,
                "openssl unavailable: cannot generate a self-signed certificate",
            )
        cfg.self_signed_cert_dir.mkdir(parents=True, exist_ok=True)
        subject = _certificate_subject_name(cfg, timeout, facts)
        try:
            run_command(
                substituted_command(
                    cfg.openssl_generate_command,
                    {
                        "subject": cfg.openssl_subject_template.format(
                            subject=subject
                        ),
                        "key_file": str(cfg.self_signed_cert_privkey),
                        "fullchain_file": str(cfg.self_signed_cert_fullchain),
                    },
                ),
                timeout=timeout,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            return False, f"cannot generate a self-signed certificate: {exc}"
        try:
            os.chmod(cfg.self_signed_cert_privkey, cfg.cert_privkey_file_mode)
            os.chmod(cfg.self_signed_cert_fullchain, cfg.cert_fullchain_file_mode)
        except OSError as exc:
            return False, f"cannot secure certificate permissions: {exc}"
    try:
        run_command(
            _panel_command(
                cfg,
                cfg.panel_certificate_command,
                fullchain=str(cfg.self_signed_cert_fullchain),
                privkey=str(cfg.self_signed_cert_privkey),
            ),
            timeout=timeout,
        )
        run_command(
            substituted_command(
                cfg.service_restart_command,
                {"service_unit_name": cfg.service_unit_name},
            ),
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        return False, f"cannot point panel at the self-signed certificate: {exc}"
    _log("self-signed certificate configured")
    return True, "self-signed certificate configured"


def _issue_trusted_cert(
    engine: EngineConfig, cfg: ThreeXuiXraySetupConfig, ip: str, timeout: float
) -> TaskResult | None:
    """Issue a trusted Let's Encrypt certificate and report the result.

    Frees the ACME port, issues the certificate through acme.sh and
    returns a TaskResult carrying the change or the warning. Shared by
    the no-certificate and the self-signed-upgrade paths of the HTTPS
    stage.
    """

    _log(f"issuing Let's Encrypt IP certificate for {ip}")
    try:
        freed = ensure_port_free(
            engine,
            cfg.acme_port,
            cfg.service_unit_name,
            timeout,
            service_process_name=cfg.service_process_name,
        )
    except RuntimeError as exc:
        return TaskResult(success=True, changed=False, warnings=(str(exc),))
    if freed:
        _log(f"ACME port {cfg.acme_port}: {freed}")
    ok, message = _issue_ip_certificate(cfg, ip, timeout)
    if not ok:
        return TaskResult(
            success=True,
            changed=False,
            warnings=(f"SSL certificate setup failed: {message}",),
        )
    _log(f"SSL certificate configured ({message})")
    return TaskResult(
        success=True, changed=True, message="SSL certificate configured"
    )


def _stage_ssl(
    engine: EngineConfig,
    cfg: ThreeXuiXraySetupConfig,
    timeout: float,
    facts: _RunFacts,
) -> TaskResult | None:
    """Ensure the panel serves HTTPS; returns a TaskResult when changed.

    When ssl_enabled is set, the panel must serve HTTPS, never plain
    HTTP. A trusted Let's Encrypt IP certificate is issued when the
    HTTP-01 challenge can reach the machine; when it cannot (the machine
    is behind NAT without a port-80 forward) a self-signed certificate
    is generated instead, so the admin traffic stays encrypted. A panel
    that already carries a foreign certificate is left alone; a
    self-signed certificate installed by this task is replaced by a
    trusted one as soon as port 80 becomes reachable. Returns None when
    nothing changed and a TaskResult with the message or the warning
    otherwise, so the caller merges it into the task result.
    """

    if not cfg.ssl_enabled:
        return None
    cert = xui_client.panel_cert_value(cfg, timeout)
    self_signed = str(cfg.self_signed_cert_fullchain)
    if cert is not None and cert != self_signed:
        _log("SSL certificate already configured")
        return None
    if cert == self_signed:
        # Our self-signed certificate is installed; only a now-reachable
        # port 80 justifies replacing it with a trusted one.
        if not _ssl_reachable(cfg, timeout, facts):
            _log("self-signed certificate already configured")
            return None
        ip = _detect_server_ip(facts)
        if ip is not None:
            return _issue_trusted_cert(engine, cfg, ip, timeout)
        return None
    ip = _detect_server_ip(facts)
    if ip is not None and _ssl_reachable(cfg, timeout, facts):
        return _issue_trusted_cert(engine, cfg, ip, timeout)
    ok, message = _ensure_self_signed_cert(engine, cfg, timeout, facts)
    if ok:
        return TaskResult(
            success=True,
            changed=True,
            message=(
                "panel serves HTTPS with a self-signed certificate; "
                "forward port 80 and re-run the task to get a trusted "
                "Let's Encrypt certificate"
            ),
        )
    if message:
        return TaskResult(
            success=True,
            changed=False,
            warnings=(f"SSL setup failed: {message}; panel serves HTTP",),
        )
    return None


def _remote_profile(
    cfg: ThreeXuiXraySetupConfig, ctx: Context
) -> tuple[routing_policy.VlessProfile | None, str]:
    """The profile of the remote server, and a reason when it is unavailable.

    The vless link comes from the entry named by
    client_profile_entry_title in the source vault, production first: the
    link is the single source of truth for the profile, because it already
    carries the REALITY public key, the short id and the spider path. The
    reason is an empty string when the profile is returned and a sentence
    for the operator when it is not, so exactly one of the two is set.
    """

    source = open_source_vault(
        ctx.repo_root, ctx.config.local_vault_setup, ctx.vault_password
    )
    if source is None:
        return None, (
            "no source vault could be opened: the local proxy is not configured"
        )
    kp, path = source
    entry = kp.find_entries(
        title=cfg.client_profile_entry_title,
        group=kp.root_group,
        recursive=False,
        first=True,
    )
    link = (entry.url or "").strip() if entry is not None else ""
    if not link:
        return None, (
            f"no vless link in {cfg.client_profile_entry_title} of {path.name}: "
            "the local proxy is not configured"
        )
    profile = routing_policy.parse_vless_link(
        link,
        cfg.remote_link_default_port,
        cfg.xray_values["vless"],
        cfg.vless_link_query_keys,
        cfg.xray_values,
    )
    if profile is None:
        return None, (
            f"the url of {cfg.client_profile_entry_title} is not a usable "
            "vless link: the local proxy is not configured"
        )
    return profile, ""


def _is_remote_server(profile: routing_policy.VlessProfile, facts: _RunFacts) -> bool:
    """True when the profile points at this machine itself.

    A machine that runs the remote server must not connect to itself, so
    the address of the link is compared with the addresses of this
    machine's interfaces and with the addresses the echo services
    reported.
    """

    if profile.address in facts.local_addresses:
        return True
    return profile.address in (
        facts.public_addresses.ipv4 + facts.public_addresses.ipv6
    )


def _stage_local_proxy(
    cfg: ThreeXuiXraySetupConfig,
    timeout: float,
) -> TaskResult | None:
    """Stage 6: serve a local proxy for this machine through the panel.

    The panel already runs Xray on this machine, so the client of the
    remote server is an inbound of that panel: one listener that serves
    SOCKS5 and HTTP on the configured local address, without a password,
    without a traffic limit and without an expiry date. The inbound is
    created once and replaced when its definition differs, so a rerun with
    another port or another sniffing set converges. It is created on every
    machine, the remote server itself included: only the connection to
    that server is left out there, and the local proxy of such a machine
    is used by the pool the subscription fills. Returns None when the
    inbound already matches, and a TaskResult carrying the change or the
    reason it could not be made.
    """

    try:
        env = xui_client.panel_environment(cfg, timeout)
    except (FileNotFoundError, RuntimeError) as exc:
        return TaskResult(
            success=True,
            warnings=(f"local proxy not configured: {exc}",),
        )
    try:
        changed, message = xray_client.ensure_local_proxy_inbound(
            cfg, env, timeout
        )
    except RuntimeError as exc:
        return TaskResult(
            success=True,
            warnings=(f"local proxy not configured: {exc}",),
        )
    if not changed:
        _log(f"local proxy {cfg.local_proxy_tag} is already configured")
        return None
    _log(
        f"local proxy {cfg.local_proxy_tag} on "
        f"{cfg.local_proxy_listen_address}:{cfg.local_proxy_port}: {message}"
    )
    return TaskResult(
        success=True,
        changed=True,
        message=(
            f"local proxy on "
            f"{cfg.local_proxy_listen_address}:{cfg.local_proxy_port} configured"
        ),
    )


def _proxy_request(
    cfg: ThreeXuiXraySetupConfig, proxy: str, url: str
) -> tuple[str, str, int]:
    """One request through the local proxy: body, HTTP code, curl exit code.

    The HTTP code comes from a write-out marker, so a refused or timed out
    transfer is reported as the configured no-answer code of the tool
    instead of being mistaken for a body. The
    request is not retried here: the caller decides how many attempts a
    check is worth, so a stalling tunnel is reported with the number of
    attempts it got instead of being hidden by a retry loop.
    """

    no_answer = cfg.tunnel_probe_no_answer_code
    try:
        result = run_command(
            substituted_command(
                cfg.tunnel_probe_command,
                {
                    "proxy_address": proxy,
                    "timeout_seconds": str(cfg.proxy_check_timeout_seconds),
                    "write_out": cfg.tunnel_probe_write_out,
                },
            )
            + [url],
            check=False,
            capture=True,
            timeout=cfg.proxy_check_command_timeout_seconds,
        )
    except (subprocess.TimeoutExpired, OSError) as exc:
        return f"the request could not be run: {exc}", no_answer, 1
    output = result.stdout
    body, _, code = output.rpartition("\n")
    return (
        trim_whitespace(body),
        trim_whitespace(code) or no_answer,
        result.returncode,
    )


def _own_addresses(facts: _RunFacts) -> tuple[str, ...]:
    """Every address this machine answers to, as the run facts know them."""

    return facts.local_addresses + facts.public_addresses.ipv4 + facts.public_addresses.ipv6


def _check_egress_address(
    cfg: ThreeXuiXraySetupConfig,
    policy: routing_policy.LocalProxyPolicy,
    profile: routing_policy.VlessProfile,
    facts: _RunFacts,
    proxy: str,
) -> tuple[str, ...]:
    """Check where a request through the local proxy leaves, per country.

    Outside Russia the policy sends an ordinary foreign name through the
    pool, whose members are the remote server and the nodes of the
    subscriptions, so any answer that is not an address of this machine is
    a working remote path and is logged with the exit it used. In Russia
    the same name is sent directly on purpose, so the answer must be an
    address of this machine: expecting the remote server there is what
    made an earlier version of this check report a working proxy as broken.
    An answer that is an address of this machine outside Russia stays the
    failure the check exists to catch, because it is the silent direct
    path. The request is attempted the configured number of times, because
    the path to a remote member can stall once and answer on the next
    attempt, which is a fact of the network rather than a reason to raise
    an alarm. It is called only for a machine that has a remote server of
    its own, so a missing remote path is never read as a defect here.
    """

    _log(f"checking where a request through {proxy} leaves")
    answer = ""
    code = 0
    http_code = cfg.tunnel_probe_no_answer_code
    attempts = cfg.proxy_check_attempts
    for attempt in range(1, attempts + 1):
        answer, http_code, code = _proxy_request(cfg, proxy, cfg.proxy_check_url)
        if code == 0 and answer:
            break
        if attempt < attempts:
            _log(
                f"attempt {attempt} of {attempts} answered nothing "
                f"(curl exit {code}), trying again"
            )
    if code != 0 or not answer:
        return (
            (
                f"the local proxy answered nothing for {cfg.proxy_check_url} "
                f"in {attempts} attempts (curl exit {code}, HTTP {http_code})"
            ),
        )
    if policy.in_russia:
        expected = (
            "an address of this machine "
            f"({', '.join(_own_addresses(facts)) or 'none known'})"
        )
        if answer in _own_addresses(facts):
            _log(
                f"the local proxy works: the request left by {answer}, "
                "directly as intended"
            )
            return ()
        if answer == profile.address:
            return (
                (
                    f"the local proxy answered {answer}, which is the remote "
                    f"server, while the policy routes {cfg.proxy_check_url} "
                    "directly: the policy may not be in place"
                ),
            )
        return (
            (
                f"the local proxy answered {answer}, while {expected} was "
                "expected: the request left somewhere unexpected"
            ),
        )
    if answer in _own_addresses(facts):
        return (
            (
                f"the local proxy answered {answer}, which is this machine: "
                "the connection did not leave by the remote path"
            ),
        )
    if answer == profile.address:
        _log(f"the local proxy works: the request left by the remote server {answer}")
    else:
        _log(
            f"the local proxy works: the request left by {answer} through "
            f"the pool {cfg.pool_balancer_tag}"
        )
    return ()


def _check_remote_path(
    cfg: ThreeXuiXraySetupConfig, proxy: str
) -> tuple[str, ...]:
    """Check that a destination the policy proxies really answers, in Russia.

    On a machine in Russia the plain check URL is routed directly, so it
    says nothing about the remote server; the check that does is a URL of a
    class the policy sends through the server, a resource blocked in Russia
    or a service that refuses to serve it. Such a service does not report
    the address of its client, so an HTTP answer is the evidence: no answer
    means the tunnel does not carry that class, which is exactly what the
    machine needs to hear. The request is attempted the configured number
    of times for the same reason as the egress check.
    """

    url = cfg.proxy_check_blocked_url
    _log(f"checking the remote path through {proxy} with {url}")
    http_code = cfg.tunnel_probe_no_answer_code
    code = 0
    attempts = cfg.proxy_check_attempts
    for attempt in range(1, attempts + 1):
        _, http_code, code = _proxy_request(cfg, proxy, url)
        if code == 0 and http_code not in (cfg.tunnel_probe_no_answer_code, ""):
            _log(f"the remote path works: {url} answered HTTP {http_code}")
            return ()
        if attempt < attempts:
            _log(
                f"attempt {attempt} of {attempts} answered nothing "
                f"(curl exit {code}), trying again"
            )
    reason = (
        f"curl exit {code}, HTTP {http_code}"
        if code != 0
        else f"HTTP {http_code}"
    )
    return (
        (
            f"the local proxy answered nothing for {url} in {attempts} "
            f"attempts ({reason}): "
            "a destination that must use the remote server does not reach it"
        ),
    )


def _check_proxy_path(
    cfg: ThreeXuiXraySetupConfig,
    policy: routing_policy.LocalProxyPolicy,
    profile: routing_policy.VlessProfile,
    facts: _RunFacts,
) -> tuple[str, ...]:
    """Prove the path of the local proxy: where it leaves and what it carries.

    The routing checks prove the decision of the core; these two prove the
    path. The first request asks an address-reporting service where the
    traffic left, and its expected answer follows from the policy: a remote
    exit outside Russia, this machine in Russia, because the policy sends
    an ordinary foreign name directly there. The second request, on a
    machine in Russia only, asks a destination that the policy sends
    through the pool whether it answers at all, so a remote path that
    carries nothing is visible instead of trusted. Both are called only
    where this machine has a remote server of its own. Every disagreement
    is returned as a warning naming what was asked, what was expected and
    what came back.
    """

    proxy = f"socks5h://{cfg.local_proxy_listen_address}:{cfg.local_proxy_port}"
    warnings = list(_check_egress_address(cfg, policy, profile, facts, proxy))
    if policy.in_russia:
        warnings.extend(_check_remote_path(cfg, proxy))
    return tuple(warnings)


def _stage_routing_policy(
    cfg: ThreeXuiXraySetupConfig,
    ctx: Context,
    timeout: float,
    facts: _RunFacts,
) -> TaskResult | None:
    """Stage 7: route the traffic of the local proxy.

    The policy decides, for every connection that enters the local proxy,
    which outbound takes it: advertising is dropped, the hidden services
    of tor and i2p go to the local proxies of those networks, the machine's
    own names and networks go directly, and the rest depends on the country
    of the machine (a machine outside Russia sends it to the remote
    server, a machine in Russia sends only what is blocked there and the
    services that refuse to serve Russia through the remote server).
    Every remote class leaves through the pool named by pool_balancer_tag:
    the pool covers the outbounds whose tags begin with pool_member_prefix,
    which are the nodes of the subscriptions the panel was given, and the
    remote outbound when this machine has one. The pool therefore exists on
    every machine and waits to be filled; on the machine that is the remote
    server itself the remote outbound is never created, so that machine
    never connects to itself, and the fallback of its pool is the direct
    outbound. The template is read, rewritten and written back only when
    something really differs, the categories are checked against the
    installed geodata first, and every class of destination is then
    verified against the running core, because the core can keep a rule set
    the stored template no longer matches. Writing the template reconciles
    the core, and the panel may do that by restarting it, so the
    verification waits for the core to answer before it asks, and a core
    that never answers is reported as such instead of as a wrong policy
    (see _wait_core_ready). The path through the local proxy is proven only
    where a remote path exists; a machine without one is told so in the log
    instead of being checked against a path it does not have. Returns None
    when everything is already in place, and a TaskResult with the change
    and the warnings otherwise.
    """

    profile, reason = _remote_profile(cfg, ctx)
    on_the_remote_server = profile is not None and _is_remote_server(profile, facts)
    remote_outbound: dict[str, object] | None = None
    if profile is None:
        _log(reason)
    elif on_the_remote_server:
        _log(
            "the profile points at this machine: the client half is configured "
            "without a connection to itself, and the remote classes wait for "
            "the pool to be filled"
        )
    else:
        remote_outbound = routing_policy.build_remote_outbound(
            cfg.remote_outbound_tag,
            profile,
            cfg.xray_field_keys,
            cfg.xray_values,
        )
    try:
        env = xui_client.panel_environment(cfg, timeout)
    except (FileNotFoundError, RuntimeError) as exc:
        return TaskResult(
            success=True,
            warnings=(f"routing policy not applied: {exc}",),
        )
    template = xui_client.read_xray_template(cfg, env, timeout)
    if template is None:
        return TaskResult(
            success=True,
            warnings=(
                (
                    "routing policy not applied: the panel did not return its "
                    "Xray configuration"
                ),
            ),
        )

    selector: tuple[str, ...] = (cfg.pool_member_prefix,)
    pool_fallback_tag = cfg.direct_outbound_tag
    if remote_outbound is not None:
        selector = (cfg.pool_member_prefix, cfg.remote_outbound_tag)
        pool_fallback_tag = cfg.remote_outbound_tag
    warnings: list[str] = []
    policy = xray_client.machine_policy(cfg, ctx, env, timeout, warnings)
    wanted, differs = xray_client.apply_policy_to_template(
        policy,
        template,
        remote_outbound=remote_outbound,
        remote_balancer_tag=cfg.pool_balancer_tag,
    )
    settings, pool_differs = routing_policy.apply_fastest_pool(
        wanted.settings,
        cfg.xray_field_keys,
        balancer=routing_policy.build_balancer(
            cfg.xray_field_keys,
            tag=cfg.pool_balancer_tag,
            selector=selector,
            strategy=cfg.xray_values["least_ping"],
            fallback_tag=pool_fallback_tag,
        ),
        observatory=routing_policy.build_observatory(
            cfg.xray_field_keys,
            subject_selector=selector,
            probe_url=cfg.pool_probe_url,
            probe_interval=cfg.pool_probe_interval,
            enable_concurrency=cfg.pool_enable_concurrency,
        ),
    )
    if pool_differs:
        wanted = replace(wanted, settings=settings)
        differs = True
    applied = False
    if differs:
        ok, message = xui_client.write_xray_template(cfg, env, wanted, timeout)
        if not ok:
            return TaskResult(
                success=True,
                warnings=tuple(warnings)
                + (f"routing policy not applied: {message}",),
            )
        applied = True
        _log(f"routing policy applied: {message}")

    failures, decided = xray_client.route_test_failures(
        cfg,
        env,
        timeout,
        policy,
        remote_balancer_tag=cfg.pool_balancer_tag,
        balancer_selector=selector,
        pool_fallback_tag=pool_fallback_tag,
    )
    if failures and decided:
        # The running core can hold a rule set the stored template no longer
        # matches, a state the panel reaches on its own after an inbound is
        # renamed. Writing the same template again is what brings the core
        # back, so it is tried once before the disagreement is reported.
        ok, message = xui_client.write_xray_template(cfg, env, wanted, timeout)
        if ok:
            applied = True
            _log(f"routing policy written again: {message}")
            failures, decided = xray_client.route_test_failures(
                cfg,
                env,
                timeout,
                policy,
                remote_balancer_tag=cfg.pool_balancer_tag,
                balancer_selector=selector,
                pool_fallback_tag=pool_fallback_tag,
            )
    warnings.extend(failures)

    # The path through the local proxy is proven only when the core decided
    # every class and this machine has a remote path at all: a core that is
    # not answering carries no traffic, and that silence is already reported
    # above. The machine that is the remote server has no remote path of its
    # own, so nothing is checked there.
    if decided and remote_outbound is not None and profile is not None:
        warnings.extend(_check_proxy_path(cfg, policy, profile, facts))
    elif decided:
        _log(
            "the path through the local proxy is not checked: this machine "
            "has no remote path of its own"
        )

    if applied:
        return TaskResult(
            success=True,
            changed=True,
            message="routing policy applied",
            warnings=tuple(warnings),
        )
    if warnings:
        return TaskResult(success=True, warnings=tuple(warnings))
    _log("routing policy is already configured and verified")
    return None


def _stage_settings(
    cfg: ThreeXuiXraySetupConfig, timeout: float
) -> tuple[bool, str] | None:
    """Move the panel subscription paths off the well-known defaults.

    Runs after stage 2, when the panel credentials are readable. Returns
    None when the paths already match the config, and (True, message)
    after writing them. Raises RuntimeError with the reason when the
    panel is unreachable or the write fails, so the caller reports a
    warning and the rest of the task continues.
    """

    try:
        env = xui_client.panel_environment(cfg, timeout)
    except (FileNotFoundError, RuntimeError) as exc:
        raise RuntimeError(str(exc)) from None
    changed, message = xui_client.ensure_subscription_paths(cfg, env, timeout)
    if not changed and not message:
        return None
    if not changed:
        raise RuntimeError(message)
    return True, message


def task(ctx: Context) -> TaskResult:
    """Wrap the official 3x-ui installer; done when the same version runs.

    The goal is reached when the installed version equals the newest
    release tag and the service is enabled and active; the task then
    returns changed=False without invoking the installer, because the
    official installer always tears the panel down and rebuilds it. A
    missing version, a version mismatch, a disabled or inactive service,
    or force mode runs the official install.sh non-interactively and
    waits for the service to become active. After the installer finishes
    (or when the target state is already reached), stage 2 reads the
    panel credentials, verifies the session through the REST API and
    stores them in the runtime vault. Stage 3 creates a VLESS+REALITY
    inbound on the configured port through the panel API; on a rerun it
    finds the existing inbound by port and returns done. Stage 5 ensures
    the panel client and stores the connection profile. Stages 6 and 7
    give this machine a local proxy and route what enters it through the
    same panel: stage 6 serves the inbound, stage 7 writes the routing
    policy together with the pool of remote exits and verifies both
    against the running core. Both stages run on every machine; the
    machine that IS the remote server never creates the outbound that
    would connect it to itself, so its pool carries the subscription
    nodes only and falls back to the direct outbound. Every step is
    reported to stdout:
    measurements and decisions as single lines that include their result,
    long-running commands as a line before and a line after. A step that
    cannot run is a warning of a completed task: a release that cannot be
    read, a busy panel or ACME port, a failed installer download, a failed
    installer run and a panel that does not become active skip the install
    alone, while the port convergence and every panel stage still run on
    the panel that is there. The runner continues with the remaining tasks
    and never stops here.
    """

    cfg = ctx.config.three_x_ui_xray_setup
    engine = ctx.config.engine
    timeout = ctx.config.engine.command_timeout_seconds
    force = ctx.task_name in ctx.force_tasks

    # Addresses and the UPnP router are read once per run: the stages below
    # reuse them, so a machine without UPnP is not asked about its router
    # for every port and the echo services are queried once.
    facts = _collect_run_facts(engine, cfg, timeout)
    facts = replace(
        facts,
        client_address=_forward_upnp_ports(engine, cfg, facts, timeout),
    )

    _log(f"querying the latest release of {cfg.github_repo}")
    tag = ""
    release: dict[str, object] = {}
    install_warnings: list[str] = []
    try:
        release = fetch_latest_release(cfg.github_repo, ctx.config.engine)
        tag = release_tag(release)
    except RuntimeError as exc:
        # Without the release tag the installed version cannot be compared,
        # so the installer is skipped; the panel that is there is still
        # converged and every stage below still runs.
        install_warnings.append(str(exc))
    if tag:
        _log(f"checking latest release: {tag}")
    else:
        _log("latest release unknown, the installer step is skipped")

    _log("reading the installed panel version")
    installed_version = _installed_version(cfg, timeout)
    _log(
        f"checking installed version: {installed_version or 'not installed'}"
    )

    enabled = service_is_enabled(ctx.config.engine, cfg.service_unit_name, timeout)
    active = service_is_active(ctx.config.engine, cfg.service_unit_name, timeout)
    _log(
        f"checking autorun service {cfg.service_unit_name}: "
        f"{'enabled' if enabled else 'disabled'}"
    )
    _log(f"checking service status: {'active' if active else 'inactive'}")

    rerun = (
        bool(tag)
        and not force
        and installed_version == version_without_tag_prefix(tag)
        and enabled
        and active
    )
    ssl_attempt = False
    if rerun:
        _log("target state already reached")
        result = TaskResult(
            success=True,
            changed=False,
            message="target state already reached",
            warnings=tuple(install_warnings),
        )
    else:
        installer_ready = bool(tag)
        if installer_ready:
            # The panel binds the fixed port, so the port must be free
            # before the installer runs: stop x-ui when it owns the port,
            # terminate an unknown process.
            _log(f"checking panel port {cfg.panel_port} is free")
            try:
                freed = ensure_port_free(
                    ctx.config.engine,
                    cfg.panel_port,
                    cfg.service_unit_name,
                    timeout,
                    service_process_name=cfg.service_process_name,
                )
            except RuntimeError as exc:
                install_warnings.append(str(exc))
                installer_ready = False
            else:
                if freed:
                    _log(f"panel port {cfg.panel_port}: {freed}")

        # Decide whether the Let's Encrypt HTTP-01 challenge can reach
        # this machine before passing XUI_SSL_MODE. A machine behind NAT
        # (only private addresses on its interfaces) cannot serve the
        # challenge unless the router forwards port 80; when it cannot,
        # the installer skips the certificate and the panel gets a
        # self-signed one after the install (stage 4), never plain HTTP.
        if cfg.ssl_enabled and installer_ready:
            ssl_attempt = _ssl_reachable(cfg, timeout, facts)

        # The installer's SSL step runs the ACME HTTP-01 challenge on
        # port 80 and fails in non-interactive mode when the port is
        # busy, so the port must be free before the installer runs.
        if installer_ready and ssl_attempt:
            _log(f"checking ACME port {cfg.acme_port} is free")
            try:
                freed = ensure_port_free(
                    ctx.config.engine,
                    cfg.acme_port,
                    cfg.service_unit_name,
                    timeout,
                    service_process_name=cfg.service_process_name,
                )
            except RuntimeError as exc:
                # Only the certificate step depends on this port: the
                # installer still runs without an SSL attempt.
                install_warnings.append(str(exc))
                ssl_attempt = False
            else:
                if freed:
                    _log(f"ACME port {cfg.acme_port}: {freed}")

        script_path: Path | None = None
        if installer_ready:
            _log(f"downloading installer {cfg.install_script_url}")
            try:
                script_path = _download_installer(
                    ctx.config.engine,
                    cfg,
                    timeout,
                )
            except RuntimeError as exc:
                install_warnings.append(str(exc))
        if script_path is None:
            result = TaskResult(
                success=True,
                changed=False,
                message="; ".join(install_warnings) or "installer skipped",
                warnings=tuple(install_warnings),
            )
        else:
            _log("installer downloaded")
            if ssl_attempt:
                _log(f"installer will attempt a certificate on port {cfg.acme_port}")

            _log("running official 3x-ui installer with proquint credentials")
            installer_env = _credential_env(cfg)
            if cfg.ssl_enabled:
                installer_env["XUI_SSL_MODE"] = "ip" if ssl_attempt else "none"
            installed_now = True
            try:
                _run_installer(cfg, script_path, timeout, installer_env)
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
                install_warnings.append(f"installer failed: {exc}")
                installed_now = False
            if not installed_now:
                result = TaskResult(
                    success=True,
                    changed=False,
                    message="; ".join(install_warnings),
                    warnings=tuple(install_warnings),
                )
            else:
                _log("installer finished")

                _log(
                    f"waiting for service to become active (up to "
                    f"{cfg.service_start_wait_seconds} s)"
                )
                if not _wait_active(
                    ctx.config.engine,
                    cfg.service_unit_name,
                    cfg.service_start_wait_seconds,
                    cfg.readiness_check_delay_seconds,
                    timeout,
                ):
                    install_warnings.append(
                        f"service {cfg.service_unit_name} did not become active "
                        f"after the installer"
                    )
                _log(f"checking installed version: {_installed_version(cfg, timeout)}")
                # Force takeover: the installer preserves credentials and
                # webBasePath on an existing non-default panel, so force applies
                # the fresh proquint values it generated for the installer
                # directly. A fresh install already received them from the
                # installer environment.
                takeover_note = ""
                if force and installed_version is not None:
                    takeover_ok, takeover_message = _takeover_credentials(
                        cfg, timeout, installer_env
                    )
                    if takeover_ok:
                        _log(takeover_message)
                        takeover_note = f"; {takeover_message}"
                    elif takeover_message:
                        install_warnings.append(
                            f"panel credential takeover failed: {takeover_message}"
                        )
                result = TaskResult(
                    success=True,
                    changed=True,
                    message=f"installed 3x-ui {tag}{takeover_note}",
                    warnings=tuple(install_warnings),
                )

    # Bring the panel to the configured port and sync install-result.env
    # so its port and scheme match reality. Runs in both paths: a rerun
    # can find a panel on a port left by an earlier install, and the
    # installer preserves an existing port on a reinstall.
    try:
        converged, converged_message = _converge_panel_port(
            ctx.config.engine, cfg, timeout
        )
    except RuntimeError as exc:
        # The panel port could not be converged: every stage below talks to
        # the panel through its REST API and reports its own result.
        install_warnings.append(str(exc))
    else:
        if converged:
            _log(f"panel port: {converged_message}")
            result.changed = True
            result.message = (result.message or "") + f"; {converged_message}"
    # A port migration restarts the panel; the HTTP listener can trail
    # the systemd active state by a moment, so stage 2 would otherwise
    # report a false login failure. Wait for the listener before it.
    _wait_panel_http(cfg, timeout)

    # Ensure the panel serves HTTPS (a trusted certificate when port 80
    # is reachable, a self-signed one otherwise) before stage 2, so the
    # stored scheme and url are correct on the first run. The stage may
    # restart the panel, so the listener is polled again after it.
    ssl_result = _stage_ssl(engine, cfg, timeout, facts)
    ssl_warnings: tuple[str, ...] = ()
    ssl_changed = False
    if ssl_result is not None:
        ssl_warnings = ssl_result.warnings or ()
        ssl_changed = ssl_result.changed
        if ssl_result.message:
            result.message = "; ".join(
                part for part in (result.message, ssl_result.message) if part
            )
        _wait_panel_http(cfg, timeout)

    # Sync install-result.env so its port and scheme match reality: the
    # port after the convergence, the scheme after the HTTPS stage set
    # the certificate.
    _sync_install_result_env(cfg, timeout)

    # Stage 2: read credentials, verify session, store in vault.
    stage2_result = _stage2(cfg, ctx.config, timeout)
    stage2_warnings: tuple[str, ...] = ()
    if stage2_result is not None:
        stage2_warnings = stage2_result.warnings or ()

    # Panel settings: move the subscription paths off the well-known
    # defaults so the panel does not warn about them. A failure here is a
    # warning, not an error: the panel keeps working with the defaults.
    settings_changed = False
    settings_warnings: tuple[str, ...] = ()
    settings_result: tuple[bool, str] | None = None
    try:
        settings_result = _stage_settings(cfg, timeout)
    except RuntimeError as exc:
        settings_warnings = (f"panel subscription paths not set: {exc}",)
    if settings_result is not None:
        settings_changed = settings_result[0]
        if settings_result[1]:
            _log(f"subscription paths: {settings_result[1]}")
            result.message = "; ".join(
                part for part in (result.message, settings_result[1]) if part
            )

    # Stage 3: create the universal server inbound. The payload document
    # comes from task_data/ of the clone, so an unreadable template is a
    # warning and the remaining stages still run.
    stage3_warnings: tuple[str, ...] = ()
    stage3_changed = False
    try:
        payload_template = _read_inbound_payload_template(cfg, ctx)
    except OSError as exc:
        stage3_warnings = (f"inbound payload template not read: {exc}",)
    else:
        stage3_result = _stage3(cfg, payload_template, timeout)
        if stage3_result is not None:
            stage3_warnings = stage3_result.warnings or ()
            stage3_changed = stage3_result.changed
            if stage3_result.message:
                result.message = "; ".join(
                    part for part in (result.message, stage3_result.message) if part
                )

    # Stage 5: ensure the panel client and store the connection profile.
    connection_result = _stage_connection(cfg, ctx.config, timeout, facts)
    connection_warnings: tuple[str, ...] = ()
    connection_changed = False
    if connection_result is not None:
        connection_warnings = connection_result.warnings or ()
        connection_changed = connection_result.changed
        if connection_result.message:
            result.message = "; ".join(
                part
                for part in (result.message, connection_result.message)
                if part
            )

    # Stage 6: serve the local proxy of this machine through the panel,
    # and stage 7: write the routing policy and the pool of remote exits
    # and verify them. Both run on every machine; the machine that is the
    # remote server itself gets no outbound to itself, so its pool falls
    # back to the direct outbound.
    proxy_result = _stage_local_proxy(cfg, timeout)
    proxy_warnings: tuple[str, ...] = ()
    proxy_changed = False
    if proxy_result is not None:
        proxy_warnings = proxy_result.warnings or ()
        proxy_changed = proxy_result.changed
        if proxy_result.message:
            result.message = "; ".join(
                part for part in (result.message, proxy_result.message) if part
            )

    routing_result = _stage_routing_policy(cfg, ctx, timeout, facts)
    routing_warnings: tuple[str, ...] = ()
    routing_changed = False
    if routing_result is not None:
        routing_warnings = routing_result.warnings or ()
        routing_changed = routing_result.changed
        if routing_result.message:
            result.message = "; ".join(
                part for part in (result.message, routing_result.message) if part
            )

    all_warnings = (
        tuple(install_warnings)
        + (result.warnings or ())
        + ssl_warnings
        + stage2_warnings
        + settings_warnings
        + stage3_warnings
        + connection_warnings
        + proxy_warnings
        + routing_warnings
    )
    if (
        all_warnings
        or ssl_changed
        or settings_changed
        or stage3_changed
        or connection_changed
        or proxy_changed
        or routing_changed
    ):
        return TaskResult(
            success=True,
            changed=(
                result.changed
                or ssl_changed
                or settings_changed
                or stage3_changed
                or connection_changed
                or proxy_changed
                or routing_changed
            ),
            message=result.message,
            warnings=all_warnings or (),
        )
    return result
