#!/usr/bin/env bash
# Thin commit command generated by the system_metrics_setup task from
# values of the system config. Publishes one regular non-empty file into
# the System Metrics spool; the ingest service moves it into the queue.
# The file is copied with mode 0600 and the commit time, then published
# atomically under the original name; a name collision is an error. The
# source file is never modified. Every action is mirrored into the
# system journal (best effort). The @SPOOL_DIR@, @JOURNAL_IDENTIFIER@
# and @TEMP_PREFIX@ markers are replaced at generation time; the rest of
# the script keeps normal bash syntax.
set -euo pipefail

SPOOL_DIR='@SPOOL_DIR@'
JOURNAL_IDENTIFIER='@JOURNAL_IDENTIFIER@'
TEMP_PREFIX='@TEMP_PREFIX@'

log_to_journal() {
    local message="$1"
    if command -v systemd-cat >/dev/null 2>&1; then
        printf '%s\n' "$message" | systemd-cat --identifier "$JOURNAL_IDENTIFIER" || true
    fi
}

fail() {
    local message="$1"
    echo "commit_system_metrics: $message" >&2
    log_to_journal "error: $message"
    exit 1
}

[[ $# -eq 1 ]] || fail "exactly one file argument expected"
file="$1"
[[ -f "$file" && -s "$file" ]] || fail "source file must be a regular non-empty file: $file"
name="$(basename -- "$file")"
[[ -n "$name" ]] || fail "source file name must not be empty"
[[ -d "$SPOOL_DIR" ]] || fail "spool directory missing: $SPOOL_DIR"

temp="$(mktemp "$SPOOL_DIR/${TEMP_PREFIX}XXXXXX")" || fail "cannot create a temporary file in $SPOOL_DIR"
trap 'rm -f -- "$temp"' EXIT
cp -- "$file" "$temp"
chmod 0600 "$temp"
touch "$temp"
if ln -- "$temp" "$SPOOL_DIR/$name" 2>/dev/null; then
    rm -f -- "$temp"
    echo "$SPOOL_DIR/$name"
    log_to_journal "committed $name into $SPOOL_DIR"
else
    fail "file already pending in the spool: $name"
fi
