# Managed by the Pyntara tor_setup task.
SocksPort 127.0.0.1:$socks_port
Log $log_level syslog
HiddenServiceDir $hidden_service_dir
HiddenServiceVersion 3
HiddenServiceNumIntroductionPoints $num_introduction_points
HiddenServicePort $onion_ssh_port 127.0.0.1:$ssh_port
